# Cloud Build configuration for deploying to Cloud Run
steps:
    # Build the container image
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/$PROJECT_ID/authentication-system-did', '.']

    # Push the container image to Container Registry
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/$PROJECT_ID/authentication-system-did']

    # Deploy container image to Cloud Run
    - name: 'gcr.io/cloud-builders/gcloud'
      args:
          - 'run'
          - 'deploy'
          - 'authentication-system-did'
          - '--image'
          - 'gcr.io/$PROJECT_ID/authentication-system-did'
          - '--region'
          - 'asia-southeast1'
          - '--platform'
          - 'managed'
          - '--allow-unauthenticated'
          - '--memory'
          - '1Gi'
          - '--cpu'
          - '1'
          - '--min-instances'
          - '1'
          - '--max-instances'
          - '10'
          - '--concurrency'
          - '80'
          - '--port'
          - '8080'

# Images to be pushed to Container Registry
images:
    - 'gcr.io/$PROJECT_ID/authentication-system-did'
