basePath: /api/v1
definitions:
  fiber.Map:
    additionalProperties: true
    type: object
  github_com_lugondev_m3-storage_internal_modules_media_domain.Media:
    properties:
      created_at:
        type: string
      file_name:
        type: string
      file_path:
        description: Path in the adapters provider
        type: string
      file_size:
        type: integer
      id:
        type: string
      media_type:
        description: e.g., image, video, document
        type: string
      provider:
        description: e.g., local, s3, azure, firebase
        type: string
      public_url:
        type: string
      updated_at:
        type: string
      uploaded_at:
        type: string
      user_id:
        type: string
    type: object
  github_com_lugondev_m3-storage_internal_modules_storage_dto.HealthCheckAllResponse:
    properties:
      providers:
        additionalProperties:
          $ref: '#/definitions/github_com_lugondev_m3-storage_internal_modules_storage_dto.HealthCheckResponse'
        type: object
    type: object
  github_com_lugondev_m3-storage_internal_modules_storage_dto.HealthCheckResponse:
    properties:
      message:
        example: ""
        type: string
      status:
        example: healthy
        type: string
    type: object
  github_com_lugondev_m3-storage_internal_modules_storage_dto.ListProvidersResponse:
    properties:
      providers:
        items:
          $ref: '#/definitions/github_com_lugondev_m3-storage_internal_modules_storage_dto.ProviderInfo'
        type: array
    type: object
  github_com_lugondev_m3-storage_internal_modules_storage_dto.ProviderInfo:
    properties:
      description:
        example: Amazon Simple Storage Service
        type: string
      name:
        example: Amazon S3
        type: string
      type:
        example: s3
        type: string
    type: object
  github_com_lugondev_m3-storage_internal_shared_errors.Error:
    properties:
      code:
        type: string
      message:
        type: string
      status_code:
        type: integer
    type: object
host: localhost:8083
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is the core API for AuthSys platform
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: AuthSys API
  version: "1.0"
paths:
  /media:
    get:
      description: Get a paginated list of media files owned by the authenticated
        user
      parameters:
      - description: 'Page number (default: 1)'
        in: query
        name: page
        type: integer
      - description: 'Number of items per page (default: 10, max: 100)'
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Paginated list of media files
          schema:
            additionalProperties: true
            type: object
        default:
          description: ""
          schema:
            $ref: '#/definitions/github_com_lugondev_m3-storage_internal_shared_errors.Error'
      security:
      - BearerAuth: []
      summary: List media files for the authenticated user with pagination
      tags:
      - Media
  /media/{id}:
    delete:
      description: Delete a specific media file by ID
      parameters:
      - description: Media ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: Media file deleted successfully
          schema:
            additionalProperties:
              type: string
            type: object
        default:
          description: ""
          schema:
            $ref: '#/definitions/github_com_lugondev_m3-storage_internal_shared_errors.Error'
      security:
      - BearerAuth: []
      summary: Delete a specific media file
      tags:
      - Media
    get:
      description: Get details of a specific media file by ID
      parameters:
      - description: Media ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Media file details
          schema:
            $ref: '#/definitions/github_com_lugondev_m3-storage_internal_modules_media_domain.Media'
        default:
          description: ""
          schema:
            $ref: '#/definitions/github_com_lugondev_m3-storage_internal_shared_errors.Error'
      security:
      - BearerAuth: []
      summary: Get a specific media file
      tags:
      - Media
  /media/{id}/file:
    get:
      description: Serve a local media file by ID for authenticated users
      parameters:
      - description: Media ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: Media file content
          schema:
            type: file
        "403":
          description: Access denied
          schema:
            $ref: '#/definitions/fiber.Map'
        "404":
          description: Media file not found
          schema:
            $ref: '#/definitions/fiber.Map'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/fiber.Map'
      security:
      - BearerAuth: []
      summary: Serve a local media file
      tags:
      - Media
  /media/public/{id}/file:
    get:
      description: Serve a local media file without authentication
      parameters:
      - description: Media ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: Media file content
          schema:
            type: file
        "404":
          description: Media file not found
          schema:
            $ref: '#/definitions/fiber.Map'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: Serve a public local media file
      tags:
      - Media
  /media/upload:
    post:
      consumes:
      - multipart/form-data
      description: Upload a file to the specified provider with optional media type
        hint
      parameters:
      - description: File to upload
        in: formData
        name: file
        required: true
        type: file
      - description: Storage provider (e.g., s3, azure, firebase, discord). If not
          specified, default provider will be used.
        in: formData
        name: provider
        type: string
      - description: Media type hint (e.g., image/jpeg, video/mp4). If not specified,
          it will be determined from the file.
        in: formData
        name: media_type
        type: string
      produces:
      - application/json
      responses:
        default:
          description: ""
          schema:
            $ref: '#/definitions/github_com_lugondev_m3-storage_internal_shared_errors.Error'
      security:
      - BearerAuth: []
      summary: Upload a file
      tags:
      - Media
  /storage/health:
    get:
      consumes:
      - application/json
      description: Check if the storage provider is healthy and accessible
      parameters:
      - description: Storage provider type
        in: query
        name: provider_type
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_lugondev_m3-storage_internal_modules_storage_dto.HealthCheckResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/github_com_lugondev_m3-storage_internal_shared_errors.Error'
      summary: Check storage provider health
      tags:
      - storage
  /storage/health/all:
    get:
      consumes:
      - application/json
      description: Check if all configured storage providers are healthy and accessible
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_lugondev_m3-storage_internal_modules_storage_dto.HealthCheckAllResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/github_com_lugondev_m3-storage_internal_shared_errors.Error'
      summary: Check all storage providers health
      tags:
      - storage
  /storage/providers:
    get:
      consumes:
      - application/json
      description: Get a list of all supported storage provider types with their information
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_lugondev_m3-storage_internal_modules_storage_dto.ListProvidersResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/github_com_lugondev_m3-storage_internal_shared_errors.Error'
      summary: List all available storage providers
      tags:
      - storage
schemes:
- http
- https
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
